name: software_licensing_client
description: A library for a software licensing system that supports local-only licenses and server-side validation.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  http: ^1.2.2
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
